<?php

/**
 * en_US.inc, US localization for dystill rule editing.
 * 
 * @author		Rob Peck <rob-dystill@robpeck.com>
 * @copyright	2011, Rob Peck.
 * @license		BSD
 * @package		dystill_roundcube
 */

$labels = array();

$labels["rules"] = "Rules";
$labels["pagetitle"] = "Rules";
$labels["rule"] = "Rule";
$labels["actions"] = "Actions";

$labels["starts_with"] = "starts with";
$labels["ends_with"] = "ends with";
$labels["contains"] = "contains";
$labels["is"] = "is";
$labels["regexp"] = "matches regular expression";

$labels["to"] = "Move to folder";
$labels["markasread"] = "Mark as read";
$labels["flag"] = "Flag";
$labels["delete"] = "Delete";
$labels["prependsub"] = "Prepend to subject: ";
$labels["header"] = "Add a header: ";
$labels["forward"] = "Forward to address: ";
$labels["block"] = "Block delivery";
$labels["blocknote"] = "Block delivery, notify sender";
$labels["copyto"] = "Copy to folder ";

$labels["value"] = "Value";
$labels["comparison"] = "Comparison";
$labels["header"] = "Header";

?>